In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/combined_emotion.csv")
df.head()

                                            sentence emotion
0      i just feel really helpless and heavy hearted    fear
1  ive enjoyed being able to slouch about relax a...     sad
2  i gave up my internship with the dmrg and am f...    fear
3                         i dont know i feel so lost     sad
4  i am a kindergarten teacher and i am thoroughl...    fear

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422746 entries, 0 to 422745
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   sentence  422746 non-null  object
 1   emotion   422746 non-null  object
dtypes: object(2)
memory usage: 6.5+ MB

In [5]:
df.columns

Index(['sentence', 'emotion'], dtype='object')

In [6]:
df.describe().T

,count,unique,top,freq
sentence,422746,393822,i feel more adventurous willing to take risks ...,16
emotion,422746,6,joy,143067

In [7]:
go = pd.read_csv("../data/preprocessed/goemotions_full_clean.csv")
go.head()

                                                text emociones_merged
0                                    That game hurt.          sadness
1     You do right, if you don't care then fuck 'em!          neutral
2                                 Man I love reddit.             love
3  [NAME] was nowhere near them, he was by the Fa...          neutral
4  Right? Considering it’s such an important docu...        gratitude