# Data Treatment & Merge

>Here we will do the final treatment to the data and merge it to a final dataframe called full-data.csv.

In [24]:
import pandas as pd
import numpy as np

## Data Importing

>We will start importing all the dataframes that we will use in this project and that has been pretreated before. We will change the name of the columns to text and emotion of each dataframe.

In [25]:
crowdflower = pd.read_csv('../data/preprocessed/crowdflower.csv',
                          names=['text', 'emotion']).drop(0).reset_index(drop=True)
go_emotions = pd.read_csv('../data/preprocessed/go-emotions.csv',
                          names=['text', 'emotion']).drop(0).reset_index(drop=True)
isear = pd.read_csv('../data/preprocessed/isear.csv', 
                    names=['text', 'emotion']).drop(0).reset_index(drop=True)
meld = pd.read_csv('../data/preprocessed/meld.csv',
                   names=['text', 'emotion']).drop(0).reset_index(drop=True)
meld_dya = pd.read_csv('../data/preprocessed/meld-dya.csv',
                       names=['text', 'emotion']).drop(0).reset_index(drop=True)
meld_emorynlp = pd.read_csv('../data/preprocessed/meld-emorynlp.csv',
                            names=['text', 'emotion']).drop(0).reset_index(drop=True)
semeval_ei = pd.read_csv('../data/preprocessed/semeval-ei.csv',
                         names=['text', 'emotion']).drop(0).reset_index(drop=True)
semeval_e = pd.read_csv('../data/preprocessed/semeval_e.csv',
                        names=['text', 'emotion']).drop(0).reset_index(drop=True)
kushagra = pd.read_csv('../data/preprocessed/kushagra.csv',
                       names=['text', 'emotion']).drop(0).reset_index(drop=True)
emotion_dataset = pd.read_csv('../data/preprocessed/emotion-dataset.csv',
                          names=['text', 'emotion']).drop(0).reset_index(drop=True)
reddit = pd.read_csv('../data/preprocessed/reddit.csv',
                          names=['text', 'emotion']).drop(0).reset_index(drop=True)

## Data Merge
>We merge all the data imported from other dataframes to a complete one named full_data before doing the final treatment to the data.

In [26]:
full_data = pd.concat([crowdflower, go_emotions, isear, meld, meld_dya, meld_emorynlp,
                       semeval_ei, semeval_e, kushagra, emotion_dataset, reddit])
full_data.head()

                                                text     emotion
0  @tiffanylue i know  i was listenin to bad habi...       empty
1  Layin n bed with a headache  ughhhh...waitin o...     sadness
2                Funeral ceremony...gloomy friday...     sadness
3               wants to hang out with friends SOON!  enthusiasm
4  @dannycastillo We want to trade with someone w...     neutral

## Data Treatment

### Duplicates cleaning

>We will start the treatment dropping the duplicates from the column text and seeing how many emotions can we find in the dataframe.

In [27]:
full_data = full_data.drop_duplicates(subset=['text'])
full_data.head()

                                                text     emotion
0  @tiffanylue i know  i was listenin to bad habi...       empty
1  Layin n bed with a headache  ughhhh...waitin o...     sadness
2                Funeral ceremony...gloomy friday...     sadness
3               wants to hang out with friends SOON!  enthusiasm
4  @dannycastillo We want to trade with someone w...     neutral

In [28]:
full_data['emotion'].unique()

array(['empty', 'sadness', 'enthusiasm', 'neutral', 'worry', 'surprise',
       'love', 'fun', 'hate', 'happiness', 'boredom', 'relief', 'anger',
       'sad', 'joy', 'fear', 'disgust', 'Joyful', 'Neutral', 'Powerful',
       'Mad', 'Sad', 'Scared', 'Peaceful', 'suprise', 'happy', 'angry',
       'rant', 'afraid', 'funny', 'surprised'], dtype=object)

### Emotion Cleaning

>As we can see, there is a lot of emotions and some of them can be treated just as one. We will only work with five emotions: joy, sad, anger, fear and surprise, so we will combine into this emotions the ones that can be used as this ones and delete the ones that don't.

In [29]:
full_data.replace(['empty', 'sadness', 'Sad'], 'sad', inplace=True)
full_data.replace(['enthusiasm', 'fun', 'happiness', 'Joyful', 'happy', 'funny', 'love'],
                  'joy', inplace=True)
full_data.replace(['worry', 'Scared', 'afraid'], 'fear', inplace=True)
full_data.replace(['suprise', 'surprised'], 'surprise', inplace=True)
full_data.replace(['hate', 'disgust', 'Mad', 'rant', 'angry'], 'anger', inplace=True)
full_data.replace(['neutral', 'boredom', 'relief', 'Neutral', 'Powerful', 'Peaceful'], 
                  np.nan, inplace=True)
full_data.dropna(inplace=True)
full_data.head()

                                                text emotion
0  @tiffanylue i know  i was listenin to bad habi...     sad
1  Layin n bed with a headache  ughhhh...waitin o...     sad
2                Funeral ceremony...gloomy friday...     sad
3               wants to hang out with friends SOON!     joy
5  Re-pinging @ghostridah14: why didn't you go to...    fear

In [30]:
full_data['emotion'].unique()

array(['sad', 'joy', 'fear', 'surprise', 'anger'], dtype=object)

>Now we only have the mentioned five emotions. And then we will also see how many data we have of each emotion.

In [31]:
full_data['emotion'].value_counts()

emotion
joy         208380
sad         132290
anger        76359
fear         60154
surprise     19039
Name: count, dtype: int64

## Data Saving

In [32]:
full_data.to_csv("../data/processed/full_data.csv", index=False)