# Data Collection

>Here we will collect all the data for the project. It will come from some pre formed dataframes with different intentions and origins like twitter, reddit, and even the sitcom "Friends", adding to this, we will scrap reddit too to also use it in this project.

In [2]:
import pandas as pd
import numpy as np

>We'll use data from studies as Crowdflower, GoEmotions, ISEAR, MELD, SemEval, one from KUSHAGRA3204 of Kaggle, Emotion Dataset from Elvis et al. and others, even our own scrap from reddit. You can find more information about this studies in the README.md of data.

>We will start reading that datasets and making one from their splits from each one. You can also find how we scrapped reddit to obtain the dataset called reddit in reddit-scrap.ipynb.

In [3]:
crowdflower = pd.read_csv('../data/raw/crowdflower.csv')

go_emotions_1 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv')
go_emotions_2 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv')
go_emotions_3 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv')
go_emotions = pd.concat([go_emotions_1, go_emotions_2, go_emotions_3])

isear = pd.read_csv('../data/raw/ISEAR.csv')

meld_train = pd.read_csv('../data/raw/MELD/MELD/train_sent_emo.csv')
meld_test = pd.read_csv('../data/raw/MELD/MELD/test_sent_emo.csv')
meld_dev = pd.read_csv('../data/raw/MELD/MELD/dev_sent_emo.csv')

meld_train_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/train_sent_emo_dya.csv')
meld_test_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/test_sent_emo_dya.csv')
meld_dev_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/dev_sent_emo_dya.csv')

meld_train_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_train_final.csv')
meld_test_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_test_final.csv')
meld_dev_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_dev_final.csv')

meld = pd.concat([meld_train, meld_test, meld_dev])
meld_dya = pd.concat([meld_train_dya, meld_test_dya, meld_dev_dya])
meld_emorynlp = pd.concat([meld_train_emorynlp, meld_test_emorynlp, meld_dev_emorynlp])

semeval_EI_anger_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-anger-train.txt', sep='\t')
semeval_EI_fear_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-fear-train.txt', sep='\t')
semeval_EI_joy_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-joy-train.txt', sep='\t')
semeval_EI_sadness_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-sadness-train.txt', sep='\t')

semeval_EI_anger_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-anger-test-gold.txt', sep='\t')
semeval_EI_fear_test= pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-fear-test-gold.txt', sep='\t')
semeval_EI_joy_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-joy-test-gold.txt', sep='\t')
semeval_EI_sadness_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-sadness-test-gold.txt', sep='\t')

semeval_EI_anger_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-anger-dev.txt', sep='\t')
semeval_EI_fear_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-fear-dev.txt', sep='\t')
semeval_EI_joy_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-joy-dev.txt', sep='\t')
semeval_EI_sadness_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-sadness-dev.txt', sep='\t')

semeval_ei = pd.concat([semeval_EI_anger_dev, semeval_EI_anger_test, semeval_EI_anger_train,
                        semeval_EI_fear_dev, semeval_EI_fear_train, semeval_EI_fear_test,
                        semeval_EI_joy_test, semeval_EI_joy_dev, semeval_EI_joy_train,
                        semeval_EI_sadness_dev, semeval_EI_sadness_test, semeval_EI_sadness_train])

semeval_e_train = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-train.txt', sep='\t')
semeval_e_test = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-test-gold.txt', sep='\t')
semeval_e_dev = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-dev.txt', sep='\t')
semeval_e = pd.concat([semeval_e_train, semeval_e_test, semeval_e_dev])

kushagra = pd.read_csv('../data/raw/combined_emotion.csv')

emotion_dataset_train = pd.read_csv('../data/raw/emotion_training.csv')
emotion_dataset_test = pd.read_csv('../data/raw/emotion_test.csv')
emotion_dataset_validation = pd.read_csv('../data/raw/emotion_validation.csv')
emotion_dataset = pd.concat([emotion_dataset_train, emotion_dataset_test, emotion_dataset_validation])

reddit = pd.read_csv('../data/raw/redditposts.csv')

## Basic Treatment

>Before starting with all the data treatment we will do some basic treatment that consists in erease unuseful columns and leave all the dataframes but semeval_e and go_emotions (we will work with them in their own data treatment notebooks due to their complexity) with only two columns that will be the text and the emotion (before processing and normalizing the emotions). We also will be showing the top 5 elements of each simplyfied DataFrame excluded the two mentioned before.

In [4]:
crowdflower.head()

                                                text       label
0  @tiffanylue i know  i was listenin to bad habi...       empty
1  Layin n bed with a headache  ughhhh...waitin o...     sadness
2                Funeral ceremony...gloomy friday...     sadness
3               wants to hang out with friends SOON!  enthusiasm
4  @dannycastillo We want to trade with someone w...     neutral

>Crowdflower comes simplyfied

In [5]:
isear.drop(['ID'], axis=1, inplace=True)
isear = isear[isear.columns[::-1]]
isear.head()

                                             content sentiment
0  At the point today where if someone says somet...     anger
1  @CorningFootball  IT'S GAME DAY!!!!      T MIN...     anger
2  This game has pissed me off more than any othe...     anger
3  @spamvicious I've just found out it's Candice ...     anger
4  @moocowward @mrsajhargreaves @Melly77 @GaryBar...     anger

>ISEAR has an useless column named ID and it has turned the text and emotion, so we erased ID and turned the DataFrame

In [6]:
meld.drop(['Sr No.', 'Speaker', 'Sentiment', 'Dialogue_ID', 'Utterance_ID', 'Season', 
           'Episode', 'StartTime', 'EndTime'], axis=1, inplace=True)
meld.head()

                                           Utterance   Emotion
0  also I was the point person on my company’s tr...   neutral
1                   You must’ve had your hands full.   neutral
2                            That I did. That I did.   neutral
3      So let’s talk a little bit about your duties.   neutral
4                             My duties?  All right.  surprise

In [7]:
meld_dya.drop(['Speaker', 'Sentiment', 'Dialogue_ID', 'Utterance_ID', 'Old_Dialogue_ID', 
               'Old_Utterance_ID', 'Season', 'Episode', 'StartTime', 'EndTime'], axis=1, inplace=True)
meld_dya.head()

                                           Utterance   Emotion
0  also I was the point person on my company’s tr...   neutral
1                   You must’ve had your hands full.   neutral
2                            That I did. That I did.   neutral
3      So let’s talk a little bit about your duties.   neutral
4                             My duties?  All right.  surprise

In [8]:
meld_emorynlp.drop(['Speaker', 'Scene_ID', 'Utterance_ID', 'Season', 
                    'Episode', 'Start_Time', 'End_Time'], axis=1, inplace=True)
meld_emorynlp.head()

                                           Utterance   Emotion
0  What you guys don't understand is, for us, kis...    Joyful
1                      Yeah, right!.......Y'serious?   Neutral
2                                          Oh, yeah!    Joyful
3  Everything you need to know is in that first k...  Powerful
4                                        Absolutely.  Powerful

>The three versions of MELD comes with a lot of useless colums to be erased.

In [9]:
for emotion in semeval_ei['Affect Dimension'].unique():
    semeval_ei.loc[semeval_ei['Intensity Class']==f'0: no {emotion} can be inferred'] = np.nan
    semeval_ei.loc[semeval_ei['Intensity Class']==f'1: low amount of {emotion} can be inferred'] = np.nan

semeval_ei.dropna(inplace=True)
semeval_ei.drop(['ID', 'Intensity Class'], axis=1, inplace=True)
semeval_ei

                                                  Tweet Affect Dimension
1     @Chan_lfc10 @paul_rule @Nuttall1878 @DeadlineD...            anger
3     #CNN really needs to get out of the #Propagand...            anger
5     Don't fucking tag me in pictures as 'family fi...            anger
7     sick of this shit. #mad #angry. Rowan Atkinson...            anger
9     I despair at the mouth foaming hostility &amp;...            anger
...                                                 ...              ...
1526  @CrystiCaro yeah agree - I think it was a fami...          sadness
1527  @wabermes The @RavalliRepublic had a good one ...          sadness
1528  If Troyler will die, I'm gonna die with them\n...          sadness
1531  Overwhelming sadness.  This too shall pass. #l...          sadness
1532  Idk why people be glorifying depression. I wou...          sadness

[4848 rows x 2 columns]

>SemEval EI has 4 intensities of emotion so we erased the ones that meant that there was no emotion infered or a low amount, after that we erased the useless columns.

In [10]:
kushagra.head()

                                            sentence emotion
0      i just feel really helpless and heavy hearted    fear
1  ive enjoyed being able to slouch about relax a...     sad
2  i gave up my internship with the dmrg and am f...    fear
3                         i dont know i feel so lost     sad
4  i am a kindergarten teacher and i am thoroughl...    fear

>Kushagra comes simplyfied

In [11]:
emotion_dataset['label'].replace([0, 1, 2, 3, 4, 5],
                                 ["sadness", "joy", "love", "anger", "fear", "surprise"],
                                 inplace= True)
emotion_dataset.head()

/tmp/ipykernel_44519/3438313263.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emotion_dataset['label'].replace([0, 1, 2, 3, 4, 5],

                                                text    label
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

>Emotion Dataset from Elvis comes with numbers instead of emotions and what each number meant so we changed the numbers for its own emotion

In [12]:
reddit.head()

                                               title emotion
0  Wanted to share my transformation from two yea...   happy
1  I'm 16, over 300lbs, and just went on my first...   happy
2              My sweet girl is CANCER FREE today!!!   happy
3  7 years ago my ex slammed my face into a bathr...   happy
4  200 days drugs free today, on my way to my fir...   happy

>We made the reddit DataFrame as the way we wanted the others to work with them, so it comes simplyfied.

## Data Saving

>We will save the simplyfied data to the subfolder preprocessed from the folder data so we can use it later to make our final dataset.

In [13]:
crowdflower.to_csv('../data/preprocessed/crowdflower.csv', index=False)
go_emotions.to_csv('../data/raw/go-emotions.csv', index=False)
isear.to_csv('../data/preprocessed/isear.csv', index=False)
meld.to_csv('../data/preprocessed/meld.csv', index=False)
meld_dya.to_csv('../data/preprocessed/meld-dya.csv', index=False)
meld_emorynlp.to_csv('../data/preprocessed/meld-emorynlp.csv', index=False)
semeval_ei.to_csv('../data/preprocessed/semeval-ei.csv', index=False)
semeval_e.to_csv('../data/raw/semeval_e.csv', index=False)
kushagra.to_csv('../data/preprocessed/kushagra.csv', index=False)
emotion_dataset.to_csv('../data/preprocessed/emotion-dataset.csv', index=False)
reddit.to_csv('../data/preprocessed/reddit.csv', index=False)

>We also added to the raw data folder the complete versions of GoEmotions and SemEval_E