>On this notebook we can see most of the emotions showed on each dataset we got imported

In [72]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\adamc\documents\github\sp-ml-17-final-project-g1\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
import pandas as pd
import numpy as np

In [74]:
crowdflower = pd.read_csv('../data/raw/crowdflower.csv')
emotions = crowdflower['label'].unique()
emotions

array(['empty', 'sadness', 'enthusiasm', 'neutral', 'worry', 'surprise',
       'love', 'fun', 'hate', 'happiness', 'boredom', 'relief', 'anger'],
      dtype=object)

In [75]:
emotion_dataset_train = pd.read_csv('../data/raw/emotion_training.csv')
emotion_dataset_test = pd.read_csv('../data/raw/emotion_test.csv')
emotion_dataset_validation = pd.read_csv('../data/raw/emotion_validation.csv')
emotion_dataset = pd.concat([emotion_dataset_train, emotion_dataset_test, emotion_dataset_validation])

'''
a classification label, with possible values including sadness (0), joy (1), love (2), anger (3), fear (4), surprise (5).
'''
emotion_dataset['label'].unique()
emotions = np.concat([emotions, [ "sadness", "joy", "love", "anger", "fear", "surprise"]])

In [76]:
go_emotions_1 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv')
go_emotions_2 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv')
go_emotions_3 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv')
go_emotions = pd.concat([go_emotions_1, go_emotions_2, go_emotions_3])
emotions = np.concat([emotions, go_emotions.columns])

In [77]:
isear = pd.read_csv('../data/raw/ISEAR.csv')
emotions = np.concat([emotions, isear['sentiment'].unique()])

In [78]:
semeval_e_train = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-train.txt', sep='\t')
semeval_e_test = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-test-gold.txt', sep='\t')
semeval_e_dev = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-dev.txt', sep='\t')
semeval_e = pd.concat([semeval_e_train, semeval_e_test, semeval_e_dev])
emotions = np.concat([emotions, semeval_e.columns])

In [79]:
semeval_EI_anger_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-anger-train.txt', sep='\t')
semeval_EI_fear_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-fear-train.txt', sep='\t')
semeval_EI_joy_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-joy-train.txt', sep='\t')
semeval_EI_sadness_train = pd.read_csv('../data/raw/English/EI-oc/training/EI-oc-En-sadness-train.txt', sep='\t')

semeval_EI_anger_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-anger-test-gold.txt', sep='\t')
semeval_EI_fear_test= pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-fear-test-gold.txt', sep='\t')
semeval_EI_joy_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-joy-test-gold.txt', sep='\t')
semeval_EI_sadness_test = pd.read_csv('../data/raw/English/EI-oc/test-gold/2018-EI-oc-En-sadness-test-gold.txt', sep='\t')

semeval_EI_anger_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-anger-dev.txt', sep='\t')
semeval_EI_fear_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-fear-dev.txt', sep='\t')
semeval_EI_joy_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-joy-dev.txt', sep='\t')
semeval_EI_sadness_dev = pd.read_csv('../data/raw/English/EI-oc/development/2018-EI-oc-En-sadness-dev.txt', sep='\t')

semeval_ei = pd.concat([semeval_EI_anger_dev, semeval_EI_anger_test, semeval_EI_anger_train,
                        semeval_EI_fear_dev, semeval_EI_fear_train, semeval_EI_fear_test,
                        semeval_EI_joy_test, semeval_EI_joy_dev, semeval_EI_joy_train,
                        semeval_EI_sadness_dev, semeval_EI_sadness_test, semeval_EI_sadness_train])

emotions = np.concat([emotions, semeval_ei['Affect Dimension'].unique()])

In [80]:
meld_train = pd.read_csv('../data/raw/MELD/MELD/train_sent_emo.csv')
meld_test = pd.read_csv('../data/raw/MELD/MELD/test_sent_emo.csv')
meld_dev = pd.read_csv('../data/raw/MELD/MELD/dev_sent_emo.csv')

meld_train_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/train_sent_emo_dya.csv')
meld_test_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/test_sent_emo_dya.csv')
meld_dev_dya = pd.read_csv('../data/raw/MELD/MELD_Dyadic/dev_sent_emo_dya.csv')

meld_train_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_train_final.csv')
meld_test_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_test_final.csv')
meld_dev_emorynlp = pd.read_csv('../data/raw/MELD/emorynlp/emorynlp_dev_final.csv')

meld = pd.concat([meld_train, meld_test, meld_dev])
meld_dya = pd.concat([meld_train_dya, meld_test_dya, meld_dev_dya])
meld_emorynlp = pd.concat([meld_train_emorynlp, meld_test_emorynlp, meld_dev_emorynlp])
emotions = np.concat([emotions, meld_emorynlp['Emotion'].unique(),
                      meld_dya['Emotion'].unique(), meld['Emotion'].unique()])

In [81]:
kushagra = pd.read_csv('../data/raw/combined_emotion.csv')
emotions = np.concat([emotions, kushagra['emotion'].unique()])

In [82]:
reddit = pd.read_csv('../data/raw/redditposts.csv')
emotions = np.concat([emotions, reddit['emotion'].unique()])
reddit.tail

<bound method NDFrame.tail of                                                    title    emotion
0      Wanted to share my transformation from two yea...      happy
1      I'm 16, over 300lbs, and just went on my first...      happy
2                  My sweet girl is CANCER FREE today!!!      happy
3      7 years ago my ex slammed my face into a bathr...      happy
4      200 days drugs free today, on my way to my fir...      happy
...                                                  ...        ...
11699  I was born without a little finger on my right...  surprised
11700                             "Not OJ" license plate  surprised
11701             I welded a rose for my mum's birthday.  surprised
11702  These two different sets of shopping baskets a...  surprised
11703            These removed fish hooks at my local ER  surprised

[11704 rows x 2 columns]>

In [83]:
np.unique(emotions)

array(['ID', 'Joyful', 'Mad', 'Neutral', 'Peaceful', 'Powerful', 'Sad',
       'Scared', 'Tweet', 'admiration', 'afraid', 'amusement', 'anger',
       'angry', 'annoyance', 'anticipation', 'approval', 'author',
       'boredom', 'caring', 'confusion', 'created_utc', 'curiosity',
       'desire', 'disappointment', 'disapproval', 'disgust',
       'embarrassment', 'empty', 'enthusiasm', 'example_very_unclear',
       'excitement', 'fear', 'fun', 'funny', 'gratitude', 'grief',
       'happiness', 'happy', 'hate', 'id', 'joy', 'link_id', 'love',
       'nervousness', 'neutral', 'optimism', 'parent_id', 'pessimism',
       'pride', 'rant', 'rater_id', 'realization', 'relief', 'remorse',
       'sad', 'sadness', 'subreddit', 'suprise', 'surprise', 'surprised',
       'text', 'trust', 'worry'], dtype=object)

In [84]:
for emotion in semeval_ei['Affect Dimension'].unique():
    semeval_ei.loc[semeval_ei['Intensity Class']==f'0: no {emotion} can be inferred'] = np.nan
    semeval_ei.loc[semeval_ei['Intensity Class']==f'1: low amount of {emotion} can be inferred'] = np.nan

semeval_ei.dropna(inplace=True)
semeval_ei.drop(['ID', 'Intensity Class'], axis=1, inplace=True)
semeval_ei

                                                  Tweet Affect Dimension
1     @Chan_lfc10 @paul_rule @Nuttall1878 @DeadlineD...            anger
3     #CNN really needs to get out of the #Propagand...            anger
5     Don't fucking tag me in pictures as 'family fi...            anger
7     sick of this shit. #mad #angry. Rowan Atkinson...            anger
9     I despair at the mouth foaming hostility &amp;...            anger
...                                                 ...              ...
1526  @CrystiCaro yeah agree - I think it was a fami...          sadness
1527  @wabermes The @RavalliRepublic had a good one ...          sadness
1528  If Troyler will die, I'm gonna die with them\n...          sadness
1531  Overwhelming sadness.  This too shall pass. #l...          sadness
1532  Idk why people be glorifying depression. I wou...          sadness

[4848 rows x 2 columns]

In [85]:
go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan
go_emotions.dropna(inplace=True)
go_emotions.drop(['id', 'author', 'subreddit', 'link_id', 'parent_id',
                  'created_utc', 'rater_id', 'example_very_unclear'], axis =1, inplace=True)
go_emotions

C:\Users\adamc\AppData\Local\Temp\ipykernel_16184\2176924920.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,"You do right, if you don't care then fuck 'em!",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Man I love reddit.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"[NAME] was nowhere near them, he was by the Fa...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,Right? Considering it’s such an important docu...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71219,"Well, I'm glad you're out of all that now. How...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71220,Everyone likes [NAME].,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71221,Well when you’ve imported about a gazillion of...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71222,That looks amazing,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71223,The FDA has plenty to criticize. But like here...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
kushagra

                                                 sentence emotion
0           i just feel really helpless and heavy hearted    fear
1       ive enjoyed being able to slouch about relax a...     sad
2       i gave up my internship with the dmrg and am f...    fear
3                              i dont know i feel so lost     sad
4       i am a kindergarten teacher and i am thoroughl...    fear
...                                                   ...     ...
422741                 i begun to feel distressed for you    fear
422742  i left feeling annoyed and angry thinking that...   anger
422743  i were to ever get married i d have everything...     joy
422744  i feel reluctant in applying there because i w...    fear
422745  i just wanted to apologize to you because i fe...   anger

[422746 rows x 2 columns]

In [87]:
emotion_dataset

                                                   text  label
0                               i didnt feel humiliated      0
1     i can go from feeling so hopeless to so damned...      0
2      im grabbing a minute to post i feel greedy wrong      3
3     i am ever feeling nostalgic about the fireplac...      2
4                                  i am feeling grouchy      3
...                                                 ...    ...
1995  im having ssa examination tomorrow in the morn...      0
1996  i constantly worry about their fight against n...      1
1997  i feel its important to share this info for th...      1
1998  i truly feel that if you are passionate enough...      1
1999  i feel like i just wanna buy any cute make up ...      1

[20000 rows x 2 columns]