In [1]:
import pandas as pd
import numpy as np

# Introduction
In this notebook we will treat the go_emotions dataset from google research to fit in our model. Our objective here is to reduce the dataset from the original size to give us only the information we need, in this case the column ['text'] and ['emotion']

##

## First step:

We load up the data and drop the columns we don't need

In [71]:
go_emotions_1 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv')
go_emotions_2 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv')
go_emotions_3 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv')
go_emotions = pd.concat([go_emotions_1, go_emotions_2, go_emotions_3])

In [72]:
go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan
go_emotions.dropna(inplace=True)
go_emotions.drop(['id', 'author', 'subreddit', 'link_id', 'parent_id',
                  'created_utc', 'rater_id', 'example_very_unclear'], axis =1, inplace=True)
go_emotions

C:\Users\nahue\AppData\Local\Temp\ipykernel_2664\2176924920.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,"You do right, if you don't care then fuck 'em!",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Man I love reddit.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"[NAME] was nowhere near them, he was by the Fa...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,Right? Considering it’s such an important docu...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71219,"Well, I'm glad you're out of all that now. How...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71220,Everyone likes [NAME].,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71221,Well when you’ve imported about a gazillion of...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71222,That looks amazing,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71223,The FDA has plenty to criticize. But like here...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Second Step:
As u can see before emotions are treated as a numerical form in a ton of columns, our goal is to have all the information only in two columns, [text] containing the message and [emotion] containing the emotion

In [73]:

df = go_emotions.copy()

In [74]:

text_col = "text"

emotion_cols = go_emotions.columns.drop('text')

In [ ]:
for col in emotion_cols:
    df[col] = df[col].replace({1: col, 0: ""})

df

In the cell below we are doing so text that only have 1 emotion saves as so and texts that have more than 1 emotion saves as a python list

In [76]:
df["emociones_merged"] = df[emotion_cols].apply(
    lambda fila: [val for val in fila if val != ""][0] if sum(fila != "") == 1 
                 else [val for val in fila if val != ""],
    axis=1
)

In [77]:
df.drop(emotion_cols, axis=1, inplace=True)

In [78]:
df

                                                    text emociones_merged
0                                        That game hurt.          sadness
2         You do right, if you don't care then fuck 'em!          neutral
3                                     Man I love reddit.             love
4      [NAME] was nowhere near them, he was by the Fa...          neutral
5      Right? Considering it’s such an important docu...        gratitude
...                                                  ...              ...
71219  Well, I'm glad you're out of all that now. How...              joy
71220                             Everyone likes [NAME].             love
71221  Well when you’ve imported about a gazillion of...           caring
71222                                 That looks amazing       admiration
71223  The FDA has plenty to criticize. But like here...            anger

[207814 rows x 2 columns]

## Final Step
We save the treated dataset in .csv

In [82]:
df.to_csv("goemotions_full_clean.csv", index=False)