In [60]:
import pandas as pd
import numpy as np

In [61]:
semeval_e_train = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-train.txt', sep='\t')
semeval_e_test = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-test-gold.txt', sep='\t')
semeval_e_dev = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-dev.txt', sep='\t')
semeval_e = pd.concat([semeval_e_train, semeval_e_test, semeval_e_dev])

### verificamos si hay columnas que no nos interesa

In [62]:
semeval_e.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2017-En-21441,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,2017-En-31535,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,2017-En-21068,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,2017-En-31436,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,2017-En-22195,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

In [63]:
semeval_e.drop(columns=['ID'], inplace=True)

In [64]:
semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

In [65]:
df= semeval_e.copy()

In [66]:
emotion_cols = semeval_e.columns.drop('Tweet')
emotion_cols

Index(['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism',
       'pessimism', 'sadness', 'surprise', 'trust'],
      dtype='object')

#### con esto reemplazamos los 1 por las emociones y los 0 desaparecen

In [67]:

for col in emotion_cols:
    df[col] = df[col].replace({1: col, 0: np.nan})

df

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,NaN,anticipation,NaN,NaN,NaN,NaN,optimism,NaN,NaN,NaN,trust
1,Whatever you decide to do make sure it makes y...,NaN,NaN,NaN,NaN,joy,love,optimism,NaN,NaN,NaN,NaN
2,@Max_Kellerman it also helps that the majorit...,anger,NaN,disgust,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN
3,Accept the challenges so that you can literall...,NaN,NaN,NaN,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN
4,My roommate: it's okay that we can't spell bec...,anger,NaN,disgust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
881,@BadHombreNPS @SecretaryPerry If this didn't m...,anger,NaN,disgust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,Excited to watch #stateoforigin tonight! Come ...,NaN,NaN,NaN,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN
883,"Blah blah blah Kyrie, IT, etc. @CJC9BOSS leavi...",anger,NaN,disgust,NaN,NaN,NaN,NaN,NaN,sadness,NaN,NaN
884,#ThingsIveLearned The wise #shepherd never tru...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885,I am really flattered and happy to hear those ...,NaN,NaN,NaN,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN

In [68]:
df.replace(['sadness', 'pessimism'], 'sad', inplace=True)
df.replace(['love', 'optimism'], 'joy', inplace=True)
df.replace(['disgust'], 'anger', inplace=True)

In [69]:
df['joy'].fillna(df['love'], inplace=True)
df['joy'].fillna(df['optimism'], inplace=True)
df['sadness'].fillna(df['pessimism'], inplace=True)
df['anger'].fillna(df['disgust'], inplace=True)
df.fillna("", inplace=True )

C:\Users\camag\AppData\Local\Temp\ipykernel_23148\2996154262.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['joy'].fillna(df['love'], inplace=True)
C:\Users\camag\AppData\Local\Temp\ipykernel_23148\2996154262.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sadness'].fillna(df['pessimism'], inplace=True)
C:\Users\camag\AppData\Local\Temp\ipykernel_23148\2996154262.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['anger'].fillna(df['disgust'], inplace=True)

In [70]:
df.drop(['anticipation', 'trust', 'love', 'optimism', 'pessimism', 'disgust'], axis=1, inplace=True)

In [71]:
final_emotions = df.columns.drop('Tweet')

In [72]:
df["emociones_merged"] = df[final_emotions].apply(
    lambda fila: [val for val in fila if val != ""][0] if sum(fila != "") == 1 
                 else [val for val in fila if val != ""],
    axis=1
)
df.head()

,Tweet,anger,fear,joy,sadness,surprise,emociones_merged
0,“Worry is a down payment on a problem you may ...,,,joy,,,joy
1,Whatever you decide to do make sure it makes y...,,,joy,,,joy
2,@Max_Kellerman it also helps that the majorit...,anger,,joy,,,"[anger, joy]"
3,Accept the challenges so that you can literall...,,,joy,,,joy
4,My roommate: it's okay that we can't spell bec...,anger,,,,,anger

### Aqui eliminamos las columnas sobrantes.

In [73]:
df.drop(columns = final_emotions, inplace=True)

In [74]:
df.head()

                                               Tweet emociones_merged
0  “Worry is a down payment on a problem you may ...              joy
1  Whatever you decide to do make sure it makes y...              joy
2  @Max_Kellerman  it also helps that the majorit...     [anger, joy]
3  Accept the challenges so that you can literall...              joy
4  My roommate: it's okay that we can't spell bec...            anger

### Ahora eliminamos la información incompleta o ambigua

In [75]:
df.emociones_merged.dropna(inplace=True)

In [76]:
def clean_lists(val):
    if isinstance(val, list):
        return np.nan
    else:
        return val

for col in df.columns:
    df[col] = df[col].apply(clean_lists)

df.dropna(inplace=True)
df

                                                 Tweet emociones_merged
0    “Worry is a down payment on a problem you may ...              joy
1    Whatever you decide to do make sure it makes y...              joy
3    Accept the challenges so that you can literall...              joy
4    My roommate: it's okay that we can't spell bec...            anger
5    No but that's so cute. Atsu was probably shy a...              joy
..                                                 ...              ...
877  Never regret anything that once made you smile...              joy
880  Being deeply loved by someone gives you streng...              joy
881  @BadHombreNPS @SecretaryPerry If this didn't m...            anger
882  Excited to watch #stateoforigin tonight! Come ...              joy
885  I am really flattered and happy to hear those ...              joy

[6081 rows x 2 columns]

In [77]:
type(df.emociones_merged[1])

pandas.core.series.Series

In [78]:
df.to_csv('../data/preprocessed/semeval-e.csv', index=False)