# Database Backup

In this notebook we will convert our full_data csv into a **SQLite Database** for backup and easier data management. Our dataset contains almost 500.000 entries with text and corresponding emotion label

In [5]:
import pandas as pd
import sqlite3

Importing the **full_data** csv

In [ ]:
csv_file = '../data/processed/full_data.csv'
df = pd.read_csv(csv_file)
df.head()

                                                text emotion
0  @tiffanylue i know  i was listenin to bad habi...     sad
1  Layin n bed with a headache  ughhhh...waitin o...     sad
2                Funeral ceremony...gloomy friday...     sad
3               wants to hang out with friends SOON!     joy
4  Re-pinging @ghostridah14: why didn't you go to...    fear

Here we create the database and start a connection to it

In [18]:
db_file = 'dataset.sqlite'
conn = sqlite3.connect(db_file)

In [8]:
df.to_sql("dataset", conn, if_exists="replace", index=False)

496222

Now I try to consult the **Database** to give me 10 anger entries

In [ ]:
anger_texts = pd.read_sql("SELECT text, emotion FROM dataset WHERE emotion = 'anger' LIMIT 10", conn)
anger_texts

                                                text emotion
0  It is so annoying when she starts typing on he...   anger
1  dammit! hulu desktop has totally screwed up my...   anger
2  @ cayogial i wanted to come to BZ this summer ...   anger
3                @mrgenius23 You win ... SIGH Rakeem   anger
4                      @soviet_star Damn, that sucks   anger
5  @mileycyrus THIS WEBSITE GAVE ME A VIRUS! When...   anger
6  @IamYeTe Waraku is tasteless and expensive! Po...   anger
7       @britblackbird  youstinkatrespondingtotexts!   anger
8  don't you hate it when you finish all your wor...   anger
9  @melluffsyew Umm yeah. That's probably a prett...   anger

We now close the connection to save memory in our project

In [16]:
conn.close()